export const translations = {
  jp: {
    seo: { title: "Omegaion（オメガイオン）| ESG・環境規制予測AI", description: "AIが多言語ソースからESG、環境問題を解析。事実をリアルタイムに可視化し、サステナビリティ・コンプライアンス業務を自動化します。", keywords: "オメガイオン, Omegaion, ESG, サステナビリティ, CSRD" },
    nav: { login: "ログイン" },
    common: { patent: "特許出願中", chapters: ["01 Visualization", "02 Solutions", "03 Rules"] },
    hero: { tag: "AI-Powered ESG Intelligence", title: "ESGコンプライアンスを自動化。", highlight: "グローバルリスク", title_suffix: "をリアルタイム監視", desc: "EUの複雑な環境規制や、サプライチェーンに潜む物理的・移行リスクをAIが瞬時に特定。リサーチにかかる膨大な工数を削減します。", cta: "無料で始める", cta_sub: "デモ動画を見る", trust_label: "信頼と準拠のグローバルスタンダード:" },
    valueProps: { tag: "WHAT YOU CAN DO", title: "複雑なESG・環境リスクを、\n直感的な『戦略』に変える。", cards: { visual: { title: "環境リスクの直感的な可視化", desc: "断片的な文字ニュースを、水・熱などの属性に分類して地図上へマッピング。見過ごされていたサプライチェーンリスクを一目で把握できます。" }, solution: { title: "AIによるソリューション提案", desc: "地図上の事象に対し、それを解決し得る世界中のクリーンテック企業や技術をAIが即座にマッチングし、具体的なアクションへと導きます。" }, regulation: { title: "複雑な規制の構造化・予測", desc: "国際機関や国ごとに散在する複雑な環境規制の動向を整理。組織単位で情報を構造化し、自社への影響を予測します。" } } },
    problem: { tag: "THE CHALLENGE", title: "膨大な規制データと\n見えないサプライチェーンリスク", desc: "ESG担当者は、断片化されたグローバルニュースと複雑な規制の追跡に、数え切れないほどの時間を奪われています。", cards: { platform: { title: "点在するデータ", desc: "グローバルな環境リスクを、単一の信頼できる情報源で監視する手段がありませんでした。" }, reality: { title: "追いつけない規制変更", desc: "CSRDやCBAMなど、日々変化し複雑化するESGフレームワークを人力で網羅するのは不可能です。" }, noise: { title: "情報のノイズ", desc: "従来の検索ではノイズが多く、自社のビジネスに直結する重大な影響を見逃す危険性があります。" }, risk: { title: "見えないリスク", desc: "遠方のサプライチェーンにおける気候変動リスクは、手遅れになるまで可視化されません。" } }, transition: "HOW OMEGAION SOLVES THIS" },
    visuals: { tag: "Core Feature 01 / 環境問題の可視化", subtag: "Environmental View", title: "文字を読む前に、\n状況を直感する。", desc: "もう地名を検索する必要はありません。8つの言語で集めた世界中の事実を、AIが地図上に直接描き出します。", elements_title: "7つの環境問題カテゴリ", elements: { water: { name: "水", desc: "洪水・干ばつ" }, heat: { name: "熱", desc: "地球温暖化" }, plants: { name: "植物", desc: "森林破壊" }, life: { name: "生き物", desc: "生物多様性" }, soil: { name: "土", desc: "砂漠化" }, ice: { name: "氷", desc: "氷河融解" }, poison: { name: "毒", desc: "汚染・廃棄物" } }, ui: { dashboard: "Omegaion News Deck", active_filters: "表示中のトピック", total_signals: "解析ニュース総数", search_placeholder: "地域・事象を検索...", heatwave: "観測史上最高気温: テキサス", flood: "大規模洪水発生: インド" } },
    features: { tag: "Core Feature 02 / SDGs AIソリューション", subtag: "Solution Proposal", title: "課題を特定し、\n解決策までたどり着く。", desc: "異変を見つけるだけで終わらせない。その問題を解決できる技術や企業をAIが自動で探し出し提案します。", advantage: "Omegaion Advantage", points: ["専門家不要で「問題特定」から「解決」まで完了", "世界中のクリーンテック企業DBと連携"], ui: { issue_label: "課題を検知", issue_val: "工業用水汚染", severity: "深刻度: 重大", solution_label: "適合ソリューション", solution_val: "高度バイオろ過装置", provider: "提供: EcoTech Global", matching: "AIマッチング" } },
    regulations: { tag: "Core Feature 03 / 地球温暖化・規制予測", subtag: "Regulatory View", title: "ルールを把握し、\nリスクを予兆で捉える。", card1: { title: "国・機関ごとのルールを構造化", desc: "世界中で生まれる新しい環境ルール。AIが国や機関ごとに整理し、事業への関わりを導き出します。" }, card2: { title: "災害リスク × 規制変化", desc: "現地の災害リスクと規制の変化を同時につかむことで、次の一手が打てるようになります。" }, ui: { stream: "世界規制ストリーム", usa: "米国 - SEC気候開示規則", eu: "EU - CBAM規制", high_impact: "高インパクト", japan: "日本 - GXリーグ" } },
    future: { tag: "Coming Soon", title: "断片的な情報が、AIによって\n『戦略的な物語』へと繋がる。", desc: "膨大なノイズから解放され、AIが多角的な因果関係を解明します。事後対応ではなく未来を予測し先手を打つ意思決定へ。", alert: { title: "Precision Alerting", subtitle: "見逃しゼロ。対応工数を90%削減する通知。", desc: "1日2回、全世界のニュースをAIがスキャンし、監視タグに関連する重要情報だけを抽出します。", features: ["リサーチ時間ゼロ", "ノイズ排除", "早期発見"] }, report: { title: "Contextual Intelligence", subtitle: "AIが因果を解明。週次戦略レポート。", desc: "複雑な絡み合いをナレッジグラフが分析。経営層へ提出可能なクオリティのレポートを生成します。", ui_input: "Knowledge Graph Analysis", ui_output: "Strategic Brief (PDF)" } },
    pricing: { title: "Plan", subtitle: "未来のパートナーへ。", founder: { name: "Founder Plan", desc: "ローンチ記念・創設メンバー限定", price: "$0", period: "/ 永久無料", note: "2026年3月31日までに登録した方は、完全無料でご利用いただけます。", features: ["環境ニュース・ソリューションの地図表示", "組織別の環境規制ニュース閲覧", "カスタムアラート機能", "戦略レポート自動生成", "すべての基本機能アクセス"], cta: "無料で登録する" }, standard: { name: "Standard Plan", price: "$5", period: "/ 月額", note: "2026年4月受付開始", features: ["環境ニュースの地図表示", "環境規制ニュース閲覧", "カスタムアラート", "戦略レポート", "基本機能アクセス"], cta: "4月1日より受付開始" }, business: { name: "Business Plan", desc: "法人向け", project: "Project (5名)", team: "Team (10名)", dept: "Dept (20名)", note: "請求書払い対応、2ヶ月分無料", cta: "お問い合わせ" } }
  },
  en: {
    seo: { title: "Omegaion | ESG Compliance & Supply Chain Risk AI", description: "Automate ESG compliance. AI monitors global environmental risks.", keywords: "ESG, Compliance, Supply Chain Risk, CSRD, AI" },
    nav: { login: "Login" },
    common: { patent: "Patent Pending", chapters: ["01 Visualization", "02 Solutions", "03 Rules"] },
    hero: { tag: "AI-Powered ESG Intelligence", title: "Automate ESG Compliance.", highlight: "Monitor Global Risks", title_suffix: "in Real-Time.", desc: "Instantly track complex EU environmental regulations and hidden supply chain risks worldwide.", cta: "Start for Free", cta_sub: "Watch Demo", trust_label: "Trusted Data & Compliance Standards:" },
    valueProps: { tag: "WHAT YOU CAN DO", title: "Turn complex ESG risks\ninto intuitive strategies.", cards: { visual: { title: "Intuitive Risk Visualization", desc: "Fragmented news is categorized and mapped to grasp supply chain risks instantly." }, solution: { title: "AI Solution Matching", desc: "AI instantly matches global environmental issues with the clean-tech companies that can solve them." }, regulation: { title: "Regulation Structuring", desc: "Organize messy regulatory updates by country to predict policy shifts." } } },
    problem: { tag: "THE CHALLENGE", title: "Regulatory overload &\nhidden supply chain risks.", desc: "ESG professionals waste countless hours tracking fragmented global news.", cards: { platform: { title: "Scattered Data", desc: "No single source of truth for global risks." }, reality: { title: "Regulatory Complexity", desc: "Hard to keep up with frameworks like CSRD." }, noise: { title: "Information Noise", desc: "Manual research brings up irrelevant info." }, risk: { title: "Invisible Risks", desc: "Supply chain risks remain hidden." } }, transition: "HOW OMEGAION SOLVES THIS" },
    visuals: { tag: "Core Feature 01", subtag: "Environmental View", title: "Intuit the situation.", desc: "AI visualizes global facts directly on the map.", elements_title: "Categories", elements: { water: { name: "Water", desc: "Floods" }, heat: { name: "Heat", desc: "Warming" }, plants: { name: "Plants", desc: "Deforestation" }, life: { name: "Living", desc: "Bio-diversity" }, soil: { name: "Earth", desc: "Desert" }, ice: { name: "Ice", desc: "Glaciers" }, poison: { name: "Poison", desc: "Pollution" } }, ui: { dashboard: "News Deck", active_filters: "Active", total_signals: "Reports", search_placeholder: "Search...", heatwave: "Heatwave", flood: "Flood" } },
    features: { tag: "Core Feature 02", subtag: "Solutions", title: "Reach solutions.", desc: "AI finds global tech to solve problems.", advantage: "Advantage", points: ["No experts needed", "Clean-tech DB"], ui: { issue_label: "DETECTED", issue_val: "Water Contamination", severity: "Critical", solution_label: "SOLUTION", solution_val: "Bio-Filtration", provider: "EcoTech", matching: "AI Match" } },
    regulations: { tag: "Core Feature 03", subtag: "Regulations", title: "Predict risks.", card1: { title: "Structured Rules", desc: "Organizes rules by country." }, card2: { title: "Risk x Regs", desc: "Act before it's too late." }, ui: { stream: "Reg Stream", usa: "USA - SEC", eu: "EU - CBAM", high_impact: "High Impact", japan: "JAPAN - GX" } },
    future: { tag: "Coming Soon", title: "Strategic story via AI.", desc: "Predict the future.", alert: { title: "Alerting", subtitle: "Zero Misses.", desc: "AI scans news.", features: ["No Research", "No Noise", "Early Detection"] }, report: { title: "Intelligence", subtitle: "Strategy Reports.", desc: "Knowledge Graphs.", ui_input: "Graph", ui_output: "Brief" } },
    pricing: { title: "Plan", subtitle: "Partners.", founder: { name: "Founder Plan", desc: "Launch Special", price: "$0", period: "/ Lifetime Free", note: "Register by Mar 31, 2026.", features: ["Map view", "Reg news", "Alerts", "Reports", "Access"], cta: "Register Free" }, standard: { name: "Standard", price: "$5", period: "/ Month", note: "April 2026", features: ["Map view", "Reg news", "Alerts", "Reports", "Access"], cta: "Available April 1st" }, business: { name: "Business", desc: "Enterprise", project: "Project", team: "Team", dept: "Dept", note: "Invoice payment", cta: "Contact Us" } }
  },
  es: {
    seo: { title: "Omegaion | Cumplimiento ESG", description: "Automatice el cumplimiento ESG.", keywords: "ESG" }, nav: { login: "Iniciar sesión" }, common: { patent: "Patente Pendiente", chapters: ["01 Visuals", "02 Solutions", "03 Rules"] },
    hero: { tag: "Inteligencia ESG", title: "Automatiza el Cumplimiento ESG.", highlight: "Riesgos Globales", title_suffix: "en Tiempo Real.", desc: "Rastree regulaciones ambientales complejas.", cta: "Comenzar Gratis", cta_sub: "Ver Demo", trust_label: "Estándares de Datos:" },
    valueProps: { tag: "QUÉ PUEDES HACER", title: "Estrategias intuitivas.", cards: { visual: { title: "Visualización", desc: "Mapas." }, solution: { title: "Soluciones", desc: "IA." }, regulation: { title: "Regulaciones", desc: "Actualizaciones." } } },
    problem: { tag: "EL DESAFÍO", title: "Sobrecarga regulatoria.", desc: "Horas perdidas.", cards: { platform: { title: "Datos Dispersos", desc: "Sin fuente única." }, reality: { title: "Complejidad", desc: "Difícil de seguir." }, noise: { title: "Ruido", desc: "Info irrelevante." }, risk: { title: "Riesgos Invisibles", desc: "Cadenas de suministro." } }, transition: "SOLUCIÓN" },
    visuals: { tag: "01", subtag: "Ambiental", title: "Intuye.", desc: "Mapas IA.", elements_title: "Categorías", elements: { water: { name: "Agua", desc: "Inundaciones" }, heat: { name: "Calor", desc: "Calentamiento" }, plants: { name: "Plantas", desc: "Deforestación" }, life: { name: "Vida", desc: "Biodiversidad" }, soil: { name: "Tierra", desc: "Desertificación" }, ice: { name: "Hielo", desc: "Glaciares" }, poison: { name: "Veneno", desc: "Contaminación" } }, ui: { dashboard: "Noticias", active_filters: "Temas", total_signals: "Informes", search_placeholder: "Buscar...", heatwave: "Calor", flood: "Inundación" } },
    features: { tag: "02", subtag: "Soluciones", title: "Encuentra soluciones.", desc: "IA encuentra tecnología.", advantage: "Ventaja", points: ["Sin expertos", "DB global"], ui: { issue_label: "PROBLEMA", issue_val: "Contaminación", severity: "Crítica", solution_label: "SOLUCIÓN", solution_val: "Filtro", provider: "EcoTech", matching: "IA" } },
    regulations: { tag: "03", subtag: "Regulaciones", title: "Comprende reglas.", card1: { title: "Reglas", desc: "IA." }, card2: { title: "Riesgos", desc: "IA." }, ui: { stream: "Flujo", usa: "EE.UU.", eu: "UE", high_impact: "Impacto", japan: "JAPÓN" } },
    future: { tag: "Próximamente", title: "Historia estratégica.", desc: "IA.", alert: { title: "Alerta", subtitle: "Cero Fallos.", desc: "IA.", features: ["Cero Tiempo", "Sin Ruido", "Detección"] }, report: { title: "Inteligencia", subtitle: "Informes.", desc: "IA.", ui_input: "Análisis", ui_output: "PDF" } },
    pricing: { title: "Plan", subtitle: "Socios.", founder: { name: "Fundador", desc: "Lanzamiento", price: "$0", period: "/ Gratis", note: "Marzo 2026.", features: ["Mapa", "Reglas", "Alertas", "Informes", "Acceso"], cta: "Gratis" }, standard: { name: "Estándar", price: "$5", period: "/ Mes", note: "Abril 2026", features: ["Mapa", "Reglas", "Alertas", "Informes", "Acceso"], cta: "Abril" }, business: { name: "Negocios", desc: "Empresas", project: "Proyecto", team: "Equipo", dept: "Depto", note: "Factura", cta: "Contacto" } }
  },
  fr: {
    seo: { title: "Omegaion | Conformité ESG", description: "Automatisez la conformité ESG.", keywords: "ESG" }, nav: { login: "Connexion" }, common: { patent: "Brevet", chapters: ["01 Visuals", "02 Solutions", "03 Rules"] },
    hero: { tag: "Intelligence ESG", title: "Conformité ESG.", highlight: "Risques Globaux", title_suffix: "en Temps Réel.", desc: "Suivez les réglementations.", cta: "Commencer", cta_sub: "Démo", trust_label: "Normes :" },
    valueProps: { tag: "FAIRE", title: "Stratégies.", cards: { visual: { title: "Visualisation", desc: "IA." }, solution: { title: "Solutions", desc: "IA." }, regulation: { title: "Règles", desc: "IA." } } },
    problem: { tag: "DÉFI", title: "Surcharge.", desc: "Heures perdues.", cards: { platform: { title: "Données", desc: "Pas de source." }, reality: { title: "Complexité", desc: "Difficile." }, noise: { title: "Bruit", desc: "Irpertinent." }, risk: { title: "Risques", desc: "Cachés." } }, transition: "SOLUTION" },
    visuals: { tag: "01", subtag: "View", title: "Visualisez.", desc: "IA.", elements_title: "Catégories", elements: { water: { name: "Eau", desc: "Inondations" }, heat: { name: "Chaleur", desc: "Réchauffement" }, plants: { name: "Plantes", desc: "Déforestation" }, life: { name: "Vie", desc: "Biodiversité" }, soil: { name: "Terre", desc: "Désertification" }, ice: { name: "Glace", desc: "Glaciers" }, poison: { name: "Poison", desc: "Pollution" } }, ui: { dashboard: "Dashboard", active_filters: "Filtres", total_signals: "Signaux", search_placeholder: "Chercher...", heatwave: "Chaleur", flood: "Inondation" } },
    features: { tag: "02", subtag: "Solutions", title: "Solutions.", desc: "IA.", advantage: "Avantage", points: ["Sans expert", "DB"], ui: { issue_label: "PROBLÈME", issue_val: "Pollution", severity: "Critique", solution_label: "SOLUTION", solution_val: "Filtre", provider: "Fournisseur", matching: "IA" } },
    regulations: { tag: "03", subtag: "Règles", title: "Règles.", card1: { title: "Globales", desc: "IA." }, card2: { title: "Risques", desc: "IA." }, ui: { stream: "Flux", usa: "USA", eu: "EU", high_impact: "Impact", japan: "Japon" } },
    future: { tag: "À venir", title: "Histoire.", desc: "IA.", alert: { title: "Alerte", subtitle: "Zéro", desc: "IA.", features: ["Zéro", "Sans Bruit", "Détection"] }, report: { title: "Rapport", subtitle: "Stratégie.", desc: "IA.", ui_input: "Input", ui_output: "Output" } },
    pricing: { title: "Plan", subtitle: "Partenaires.", founder: { name: "Fondateur", desc: "Lancement", price: "$0", period: "/ Gratuit", note: "Mars 2026.", features: ["Carte", "Règles", "Alertas", "Rapports", "Accès"], cta: "Gratuit" }, standard: { name: "Standard", price: "$5", period: "/ Mois", note: "Avril 2026", features: ["Carte", "Règles", "Alertas", "Rapports", "Accès"], cta: "Avril" }, business: { name: "Business", desc: "Entreprise", project: "Projet", team: "Équipe", dept: "Dept", note: "Facture", cta: "Contact" } }
  },
  pt: {
    seo: { title: "Omegaion | Conformidade ESG", description: "Conformidade ESG.", keywords: "ESG" }, nav: { login: "Entrar" }, common: { patent: "Patente", chapters: ["01 Visuals", "02 Solutions", "03 Rules"] },
    hero: { tag: "Inteligência ESG", title: "Conformidade ESG.", highlight: "Riscos Globais", title_suffix: "em Tempo Real.", desc: "Acompanhe regulamentações.", cta: "Comece Grátis", cta_sub: "Demo", trust_label: "Padrões:" },
    valueProps: { tag: "FAZER", title: "Estratégias.", cards: { visual: { title: "Visualização", desc: "IA." }, solution: { title: "Soluções", desc: "IA." }, regulation: { title: "Regras", desc: "IA." } } },
    problem: { tag: "DESAFIO", title: "Sobrecarga.", desc: "Horas perdidas.", cards: { platform: { title: "Dados", desc: "Sem fonte." }, reality: { title: "Complexidade", desc: "Difícil." }, noise: { title: "Ruído", desc: "Irrelevante." }, risk: { title: "Riscos", desc: "Ocultos." } }, transition: "SOLUÇÃO" },
    visuals: { tag: "01", subtag: "View", title: "Visualize.", desc: "IA.", elements_title: "Categorias", elements: { water: { name: "Água", desc: "Inundações" }, heat: { name: "Calor", desc: "Aquecimento" }, plants: { name: "Plantas", desc: "Desmatamento" }, life: { name: "Vida", desc: "Biodiversidade" }, soil: { name: "Terra", desc: "Desertificação" }, ice: { name: "Gelo", desc: "Glaciares" }, poison: { name: "Veneno", desc: "Poluição" } }, ui: { dashboard: "Dashboard", active_filters: "Filtros", total_signals: "Sinais", search_placeholder: "Buscar...", heatwave: "Calor", flood: "Inundação" } },
    features: { tag: "02", subtag: "Soluções", title: "Soluções.", desc: "IA.", advantage: "Vantagem", points: ["Sem especialista", "DB"], ui: { issue_label: "PROBLEMA", issue_val: "Poluição", severity: "Crítico", solution_label: "SOLUÇÃO", solution_val: "Filtro", provider: "Fornecedor", matching: "IA" } },
    regulations: { tag: "03", subtag: "Regras", title: "Regras.", card1: { title: "Globais", desc: "IA." }, card2: { title: "Riscos", desc: "IA." }, ui: { stream: "Fluxo", usa: "USA", eu: "EU", high_impact: "Impacto", japan: "Japão" } },
    future: { tag: "Em breve", title: "História.", desc: "IA.", alert: { title: "Alerta", subtitle: "Zero", desc: "IA.", features: ["Zero", "Sem Ruído", "Detecção"] }, report: { title: "Relatório", subtitle: "Estratégia.", desc: "IA.", ui_input: "Input", ui_output: "Output" } },
    pricing: { title: "Plano", subtitle: "Parceiros.", founder: { name: "Fundador", desc: "Lançamento", price: "$0", period: "/ Grátis", note: "Março 2026.", features: ["Mapa", "Regras", "Alertas", "Relatórios", "Acesso"], cta: "Grátis" }, standard: { name: "Padrão", price: "$5", period: "/ Mês", note: "Abril 2026", features: ["Mapa", "Regras", "Alertas", "Relatórios", "Acesso"], cta: "Abril" }, business: { name: "Negócios", desc: "Empresa", project: "Projeto", team: "Equipe", dept: "Dept", note: "Fatura", cta: "Contato" } }
  }
};